In [3]:
import pandas as pd
import seaborn as sns

In [4]:
df=sns.load_dataset('taxis')

In [6]:
df.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

In [7]:
df[['pickup_borough']].unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [17]:
unique_1=df[['pickup_borough']].drop_duplicates()

In [13]:
unique_1

    pickup_borough
0        Manhattan
10          Queens
42             NaN
92           Bronx
114       Brooklyn

In [16]:
unique_2=df['pickup_borough'].unique()
unique_2

<StringArray>
['Manhattan', 'Queens', nan, 'Bronx', 'Brooklyn']
Length: 5, dtype: str

* `df['pickup_borough'].unique()` → returns unique values as a **NumPy array**. Fast and simple.
* `df[['pickup_borough']].drop_duplicates()` → returns unique rows as a **DataFrame**, preserving index and column structure.

Use:

* `.unique()` for quick value lists
* `.drop_duplicates()` for DataFrame/table operations